import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
df = pd.read_csv(r'C:\Users\Moses Tumbo\OneDrive\Documents\data anaylysis\train.csv')
print(df.describe())
print(df.isnull().sum())
df.drop(columns=['Cabin'],inplace=True)
print(df.isnull().sum())
df['Age'].fillna(df['Age'].median(), inplace=True)
print(df.isnull().sum())
df['Embarked']=df['Embarked'].replace({'62':'s','830':'s'}).fillna('unkown')
print(df.isnull().sum())
print(df.duplicated().sum())
df.plot()
plt.show()
df.plot(kind='scatter', x='Age', y='Fare')
plt.show()
df["Age"].plot(kind='hist')
plt.show()
df["Sex"].value_counts().plot(kind='pie')
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()